version: '3'
services:
  db:
    image: mysql:8.0.18
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    networks:
      - meshireach
    environment:
      MYSQL_DATABASE: meshireach
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
    command: mysqld
  api:
    build: .
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - ./:/go/meshireach
    networks:
      - meshireach
    environment:
      GO111MODULE: "on"
      CGO_ENABLED: 0
  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - ./docs/docs.yaml:/usr/share/nginx/html/docs.yaml
    ports:
      - 8080:8080
    networks:
      - meshireach
    environment:
      API_URL: docs.yaml

volumes:
  mysql_data:
    driver: "local"

networks:
  meshireach:
    external: true
