version: 2.1
executors:
  default: circleci/golang:1.12
  working_directory: /go/src/github.com/sunflower-atelier/meshireach
  environment:
    - GO111MODULES: "on"
jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      - run:
        name: Vendoring
        command: go mod download
  test:
    executor:
      name: default
    steps:
      - run:
        name: Testing main.go
        command: go test

