swagger: "2.0"
info:
  description: "メシリーチサーバーサイドのAPIドキュメントです．"
  version: "0.0.1"
  title: "Meshireach"
  termsOfService: ""
host: "localhost:3000"
basePath: "/"

tags:
- name: "profile"
  description: "ユーザーのプロフィール"

schemes:
- "https"
- "http"

paths:
  /profiles:
    post:
      tags:
      - "profile"
      summary: "プロフィールを追加"
      description: ""
      operationId: "createProfile"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "追加するユーザーの情報"
        required: true
        schema:
            title: success
            type: object
            properties:
              searchID:
                type: string
                example: "meshi"
              name:
                type: string
                example: "meshi reach"
              message:
                type: string
                example: "yoro"
      responses:
        201:
          description: "Created"
          schema:
            title: success
            type: object
            properties:
              status:
                type: string
                example: "success"
              searchID:
                type: string
                example: "meshi"
              name:
                type: string
                example: "meshi reach"
              message:
                type: string
                example: "yoro"
        400:
          description: "Bad Request"
          schema:
            title: fail
            type: object
            properties:
              status:
                type: string
                example: "fail"
              error:
                type: string
                example: "Search ID is not unique."
    put:
      tags:
      - "profile"
      summary: "プロフィールを編集"
      description: ""
      operationId: "updateProfile"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "編集するユーザーの情報"
        required: true
        schema:
            title: success
            type: object
            properties:
              searchID:
                type: string
                example: "meshi"
              name:
                type: string
                example: "meshi reach"
              message:
                type: string
                example: "yoro"
      responses:
        200:
          description: "OK"
          schema:
            title: success
            type: object
            properties:
              status:
                type: string
                example: "success"
              searchID:
                type: string
                example: "meshimeshi"
              name:
                type: string
                example: "meshi reach"
              message:
                type: string
                example: "yoro"
        400:
          description: "Bad Request"
          schema:
            title: fail
            type: object
            properties:
              status:
                type: string
                example: "fail"
              error:
                type: string
                example: "Search ID is not unique."
                
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"

definitions:
  Profile:
    type: "object"
    required:
    - "name"
    - "photoUrls"
    properties:
      FirebaseID:
        type: "string"
        format: "string"
        example: "gahoehjqorijo1039u4i1nekfdj1"
      SearchID:
        type: "string"
        format: "string"
        description: "ユーザーが使うID"
        example: "meshimeshi"
      Name:
        type: "string"
        example: "群青 ひまわり"
      Message:
        type: "string"
        description: "ひとこと"
        example: "よろしく"
